linters:
  presets:
    - bugs
    - format
    - performance
    - style

  disable:
    - exhaustivestruct
    - exhaustruct
    - gci
    - gochecknoglobals
    - golint
    - ifshort
    - interfacer
    - maligned
    - nlreturn
    - nosnakecase
    - scopelint
    - varnamelen
    - wsl
