verbose: True # Optional

# cron: "* * * * *" # Optional, run every minute

health_check:
  url: "" # Optional, endpoint to send GET request to on a successful run

notifiers: # Optional, see https://github.com/containrrr/shoutrrr/blob/main/docs/services/overview.md for supported URL's
  - name: email_technical_en
    url: smtp://smpt4dev:smpt4dev@localhost:8025/?from=delic@localhost&to=admin1@localhost,admin2@localhost&usehtml=true&subject=Broken%20links%20found
    template_name: "technical_en" # Currently only "technical_en" and "simple_nl" supported
  - name: email_simple_nl
    url: smtp://smpt4dev:smpt4dev@localhost:8025/?from=delic@localhost&to=user@localhost&usehtml=true&subject=Defecte%20links%20gevonden
    template_name: "simple_nl" # Currently only "technical_en" and "simple_nl" supported

sites:
  - url: http://localhost:9080
    ignored_links:
      - ^http://localhost:9082
    notify: # Optional, send notification to these notification_urls by name
      - email_technical_en
      - email_simple_nl
